server:
  port: 8085
open:
  api:
    key: "your key"


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
